<a href="https://colab.research.google.com/github/ClauBDA/metop/blob/master/DataCenso2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


array = np.array([
                 ["Comuna 01", 221001, 2093, 460],
                 ["Comuna 02", 160609, 999, 37],
                 ["Comuna 03", 193537, 2455, 248],
                 ["Comuna 04", 227024, 1596, 620],
                 ["Comuna 05", 192449, 1812, 10],
                 ["Comuna 06", 201764, 1237, 42],
                 ["Comuna 07", 213262, 2366, 268],
                 ["Comuna 08", 203888, 181, 298],
                 ["Comuna 09", 167908, 1130, 25],
                 ["Comuna 10", 171896, 1036, 72],
                 ["Comuna 11", 201905, 2685, 11],
                 ["Comuna 12", 235364, 1505, 18],
                 ["Comuna 13", 262330, 1895, 160],
                 ["Comuna 14", 247252, 1300, 83],
                 ["Comuna 15", 195265, 1560, 51]])

columnas = ["Comuna", " Pob.viviendasparticulares", " Pob.viviendascolectivas", " Pob.situacióndecalle"]

dfVivienda = pd.DataFrame(array, columns=columnas)
dfVivienda

# La cantidad de poblacion encontrada en las tres situaciones de vivienda
##########################

array2 = np.array([
                 ["Comuna 01", 35],
                 ["Comuna 02", 38],
                 ["Comuna 03", 38],
                 ["Comuna 04", 35],
                 ["Comuna 05", 40],
                 ["Comuna 06", 41],
                 ["Comuna 07", 40],
                 ["Comuna 08", 32],
                 ["Comuna 09", 39],
                 ["Comuna 10", 41],
                 ["Comuna 11", 42],
                 ["Comuna 12", 40],
                 ["Comuna 13", 41],
                 ["Comuna 14", 39],
                 ["Comuna 15", 39]])

columnas2 = ["Comuna", "Edad Mediana de la población"]
dfEdadMediana = pd.DataFrame(array2, columns=columnas2)
dfEdadMediana

#
#Es la edad que divide a la población en dos grupos de igual número de personas
#

array3 = np.array([
                 ["Comuna 01", 117091, 106003],
                 ["Comuna 02", 91064, 70544],
                 ["Comuna 03", 105767, 90225],
                 ["Comuna 04", 120779, 107841],
                 ["Comuna 05", 106190, 88071],
                 ["Comuna 06", 111672, 91329],
                 ["Comuna 07", 115575, 100053],
                 ["Comuna 08", 107181, 96888],
                 ["Comuna 09", 89256, 79782],
                 ["Comuna 10", 92246, 80686],
                 ["Comuna 11", 109032, 95558],
                 ["Comuna 12", 127212, 109657],
                 ["Comuna 13", 145104, 119121],
                 ["Comuna 14", 137401, 111151],
                 ["Comuna 15", 105737, 91088]])

columnas3 = ["Comuna", "Mujer", "Varón"]
dfSexo = pd.DataFrame(array3, columns=columnas3)
dfSexo

#### Poblacion por sexo registrado al nacer
#######


array4 = np.array([
                 ["Comuna 01", 95168, 102466],
                 ["Comuna 02", 78836, 62285],
                 ["Comuna 03", 80686, 92706],
                 ["Comuna 04", 124175, 75700],
                 ["Comuna 05", 95935, 77035],
                 ["Comuna 06", 114254, 68160],
                 ["Comuna 07", 120888, 70517],
                 ["Comuna 08", 128989, 50850],
                 ["Comuna 09", 98665, 49896],
                 ["Comuna 10", 102434, 51893],
                 ["Comuna 11", 125023, 56494],
                 ["Comuna 12", 138994, 72754],
                 ["Comuna 13", 149059, 87053],
                 ["Comuna 14", 125784, 93011],
                 ["Comuna 15", 107779, 66291]])

columnas4 = ["Comuna", "Poblacion con propiedad propia", "Poblacon con propiedad alquilada"]
dfPropiedad = pd.DataFrame(array4, columns=columnas4)
dfPropiedad

#### Poblacion con un regimen de tenencia de la propiedad, hay un residual que se dejo de lado.
###

#Sigo mañana con salud